apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: p7
spec:
  selector: { 
    app: db 
  }
  ports:
    - port: 5432
      targetPort: 5432

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: p7
spec:
  replicas: 1
  selector:
    matchLabels: { 
      app: db 
    }
  template:
    metadata:
      labels: { 
        app: db 
      }
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      dnsConfig:
        nameservers:
          - 1.1.1.1
          - 8.8.8.8
      hostNetwork: true
      nodeSelector:
        node-role: database
      containers:
        - name: postgres
          image: postgres:18-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: DATABASE_NAME
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: DATABASE_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: DATABASE_PASSWORD
            - name: PGDATA
              value: /var/lib/postgresql/data
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql
          readinessProbe:
            exec:
              command: ["/bin/sh","-c","pg_isready -U \"$POSTGRES_USER\" -d \"$POSTGRES_DB\""]
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            exec:
              command: ["/bin/sh","-c","pg_isready -U \"$POSTGRES_USER\" -d \"$POSTGRES_DB\""]
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              cpu: "16000m"
              memory: "64Gi"
            limits:
              cpu: "16000m"
              memory: "64Gi"
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: pgdata