apiVersion: v1
kind: Service
metadata:
  name: adminer
  namespace: p7
spec:
  selector: { 
    app: adminer 
  }
  ports:
    - port: 8080
      targetPort: 8080
      name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
  namespace: p7
spec:
  replicas: 1
  selector:
    matchLabels: { 
      app: adminer 
    }
  template:
    metadata:
      labels: { 
        app: adminer 
      }
    spec:
      nodeSelector:
        node-role: master
      containers:
        - name: adminer
          image: adminer:latest
          ports:
            - containerPort: 8080
          env:
            - name: ADMINER_DEFAULT_SERVER
              value: db
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"